#
#  define data directories - this is the only file that you should have to change to run this code
#
# This SWVF_dir directory holds files that are too large to store in github, specifically:
#   SWVF_1_22.txt,	SWVF_45_66.txt,  SWVF_23_44.txt				SWVF_67_88.txt	(roughly 1 Gb each)
#       Found at:  https://www6.ohiosos.gov/ords/f?p=VOTERFTP:STWD:::#stwdVtrFiles
#
#    statewideresultsbyprecinct2020.xlsx (22 Mb) - this has been renamed to include the year in the name 
#       Found at: https://www.ohiosos.gov/globalassets/elections/2020/gen/statewideresultsbyprecinct.xlsx 
#    County2020RaceResultsByPrecinct.xlsx (75 Mb) - this has been renamed to include the year in the name 
#       Found at: ftp://sosftp.sos.state.oh.us/free/publications/website/results/CountyRaceResultsByPrecinct.xlsx
#
# This SWVF_dir directory also holds one file, aSWVFcolumns.rds (281 Mb), which is
#   generated by collapseOhioVoterFile.R from SWVF_1_22.txt,	SWVF_45_66.txt,  SWVF_23_44.txt and	SWVF_67_88.txt

SWVF_dir = "/Users/kenstanley/Downloads/Jan2021/" 
data_in_dir = "/Users/kenstanley/GitRepository/github/politicalRcode/OhioElectionStudy/electionData"

working_data_dir = "/Users/kenstanley/GitRepository/github/politicalRcode/OhioElectionStudy"

